config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: %i[index show new create] do
    resources :doses, only: %i[new create]
  end
  resources :doses, only: [:destroy]
  root to: 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :ingredient, presence: true
  validates :cocktail, presence: true, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Turbolinks::Redirection
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses.controller.rb
class DosesController < ApplicationController
  def show
    @dose = Dose.find(params[:id])
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to @dose.cocktail
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="csrf-param" content="authenticity_token" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" media="all" href="/assets/application.scss" />
  </head>

<body>
  <div class="banner d-flex" background-size="cover" style="background-image: url(https://images.unsplash.com/photo-1560508180-03f285f67ded?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80)">
   <div class="container">
    <h1>When Life Gives You Lemons Make Yourself A Margarita!</h1>
      <%= link_to cocktails_path, class: "navbar-brand" do %>
      <% end %>
       <%= link_to "Add New Cocktail", new_cocktail_path(@cocktail), class: "btn btn-banner" %>
   </div>
  </div>

  <div class="navbar navbar-expand-sm navbar-light">
      <%= link_to cocktails_path, class: "navbar-brand" do %>
      <% end %>
  </div>

<div class="card-deck">
  <% @cocktails.each do |cocktail| %>

    <div class="card">
      <%= cl_image_tag cocktail.photo.key, width: 364, height: 180, crop: :lfill %>
      <div class="card-body">
        <h5> <%= link_to cocktail.name, cocktail_path(cocktail), class: "card-title" %></h5>
      </div>
    </div>
  <% end %>
</div>

</body>

app/views/cocktails/new.html.erb
<body>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1568926825354-c277ddca9bec?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=748&q=80);">
     <div class="container ml-6 mt-3">
      <h1>Create a cocktail</h1>
      <%= simple_form_for [@cocktail] do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "create", class: "btn btn-banner" %>
    <% end %>
   </div>
</div>
</body>
<br>
<br>
<br>

<div class="d-flex justify-content-center">
  <%= link_to "Home", cocktails_path, class: "btn btn-ghost" %>
</div>

</body>

app/views/cocktails/show.html.erb
<body>
<div class="container ml-6 mt-3">

  <h1 class="text-black text-center" style = "font-family: 'Abril Fatface', cursive;"><%= @cocktail.name %></h1>
  <div class="d-flex justify-content-center">
    <div class="big-card">
    <%= cl_image_tag @cocktail.photo.key, width:364, height: 450,  crop: :lfill %>
    <div class="card">
        <h5 class="card-header" style = "font-family: 'Abril Fatface', cursive;">Ingredients</h5>
        <div class="card-body">
      <% @cocktail.doses.each do |dose| %>
        <p class="card-text d-flex-inline"><%= "#{dose.description} #{dose.ingredient.name}" %>
        <span class="badge badge-pill"><%= link_to 'delete', dose_path(dose), method: 'DELETE'%></span></p>
      <% end %>
    </div>
  </div>
</div>
</body>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/new.html.erb
<div class="container ml-6 mt-3">
  <h1>Create a dose</h1>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.submit "add a dose", class: "btn", style: "background-color: #7FD2ED" %>
  <% end %>
</div>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' defer: true %>
  </head>

  <body>
      <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>  <!-- from app/javascript/packs/application.js -->
  </body>

</html>